Allow application/geo+json response types
cellular/oazapfts pull request #258
Opened 2022-07-18 10:08 UTC by olof-nord

Some well defined apis define their geojson types in OpenAPI specs, and those may be of the type application/geo+json: https://datatracker.ietf.org/doc/html/rfc7946. 

This include some of the API specs I am using, which when using this type today to render TS oazapfts ends up using the Blob data type.

This PR adds support for this content type just as it has for application/hal+json and application/problem+json.

In short, this PR is based on the recently merged https://github.com/cellular/oazapfts/pull/197 one.

2022-07-22 05:03 UTC, shocklateboy92 requested changes
Hi @olof-nord and thanks for your PR!

The change seems sensible, but could you please add a test that covers the new behavior.

2022-07-23 11:27 UTC, jonkoops commented
I'm starting to think that we should perhaps change this to some kind of regular expression that checks the mime type for `application/*+json`, or perhaps provide an option to pass a function that allows the mime-type to be checked in user-space.

2022-07-26 06:13 UTC, shocklateboy92 approved these changes
I'm actually okay with this. We can do a regex if the cases get too unwieldy.
Also happy this increases our test coverage (I think) :test_tube: 

However, I'll give a few days before merging so @jonkoops can chime in if he feels strongly about the regex.

2022-07-26 09:00 UTC, jonkoops approved these changes
LGTM

2022-07-26 09:01 UTC, merged

2022-07-26 09:01 UTC, jonkoops commented
I think extending this for now is more than fine, but might get unwieldy as we go.

2022-07-26 13:04 UTC, olof-nord commented
Thanks for the good feedback, always happy to increase that test coverage 👍